version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: property_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - 
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://18.218.213.59/5000/api
      REACT_APP_AUTH_Utl: http://18.218.213.59/5000/api/users

  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgre@db:5434/property_management
      PORT: 5000
      JWT_SECRET: 201088JAH
      JWT_REFRESH_SECRET: 201088JAH
      EMAIL_USER: jordanh316@gmail.com
      EMAIL_PASS: BentleySheridan07
    ports:
      - "5000:5000"
    command: ["node", "server.js"]

volumes:
  pgdata:
