

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2284
      POSTGRES_DB: PDL_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:2284@db:5432/PDL_development
      PORT: 5000
      JWT_SECRET: your_jwt_secret
      JWT_REFRESH_SECRET: your_refresh_secret
      EMAIL_USER: jordanh316@gmail.com
      EMAIL_PASS: Bentley07Sheridan
    ports:
      - "5000:5000"
    command: ["node", "server.js"]

volumes:
  pgdata:
