const { sendEmail } = require('../services/emailService');

// ...existing code...

const yourFunction = async (req, res) => {
    // ...existing code...
    await sendEmail('recipient@example.com', 'Subject', 'Email body text');
    // ...existing code...
};

// ...existing code...
