
jobs:
  deploy:
    runs-on: ubuntu-latest

  services:
      backend:
        build:
          context: ./backend
        ports:
          - "5000:5000"
        environment:
          - NODE_ENV=production
        depends_on:
          - db
        restart: unless-stopped

      frontend:
        build:
          context: ./frontend
        ports:
          - "80:80" # expose the frontend
        depends_on:
          - backend
        restart: unless-stopped

      db:
        image: postgres:15
        ports:
          - "5434:5432"
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        volumes:
          - pgdata:/var/lib/postgresql/data
        restart: unless-stopped
    volumes:
      pgdata:
